
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    entrypoint: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
      
  taskiq-worker:
    build:
      context: .
    command: taskiq worker -tp=app/tasks/*.py -tp=app/tasks/**/*.py --reload --log-level=DEBUG app.tq:broker
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=${REDIS_URL}
    env_file:
      - .env
    depends_on:
      - web
      - redis
    restart: unless-stopped

  taskiq-scheduler:
    build:
      context: .
    command: taskiq scheduler -tp=app/tasks/*.py -tp=app/tasks/**/*.py --log-level=DEBUG app.tq:scheduler
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=${REDIS_URL}
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - taskiq-worker
    restart: unless-stopped
    
